######################################################################
# Automatically generated by qmake (2.01a) mer. 18. juin 11:49:49 2008
######################################################################

QT += network webkit
TARGET = zNavigo
TEMPLATE = app
SOURCES += FenPrincipale.cpp main.cpp
HEADERS += FenPrincipale.h
