######################################################################
# Automatically generated by qmake (2.01a) sam. 27. févr. 00:13:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += FenPrincipale.h
SOURCES += FenPrincipale.cpp main.cpp
